### ISSUE TITLE
UI todo

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/model-viewer#183]
This ticket lists the relatively small outstanding work items which remain after the recent UI refresh:
- [ ] add hierarchy search
- [ ] show names of loaded files
- [ ] show versions of editor, engine, pcui
- [ ] show github links to engine & pciu
- [ ] show bound of currently selected node
- [ ] name screenshot download based on loaded filename
- [ ] remove animations correctly when loading new file
- [ ] handle hierarchy node deselection
- [ ] review animation controls
- [ ] support camera frame of scene / currently selected node
